# Configurations
title: Blog
longtitle: SeungMin
author: SeungMin
email: 0283esm@naver.com
description: 개발자 호꼼의 블로그입니다!

version: 1.0
gitbook_version: 3.2.3

url: "https://esm712.github.io"
baseurl: "/web"
rss: RSS

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

lang: en

timezone: Asia/Seoul

toc:
  enabled: true
  h_min: 1
  h_max: 3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path: assets/gitbook/images/hokkom.ico

# markdown render engine.
markdown: kramdown
kramdown:
  auto_ids: true
  input: GFM
  math_engine: mathjax
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    guess_lang: true

syntax_highlighter_style: colorful

markdown_ext: markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink: /:categories/:year-:month-:day-:title:output_ext

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts

collections:
  pages:
    output: false
    permalink: /:collection/:path/
  java:
    output: true
    permalink: /:collection/:path/
  SQL:
    output: true
    permalink: /:collection/:path/
  books:
    output: true
    permalink: /:collection/:path/
  others:
    output: true
    permalink: /:collection/:path/

ordered_collections:
  - pages
  - java
  - SQL
  - books
  - others

page_width: 800px

destination: ./_site
incremental: false
regenerate: true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji

github_username: esm712
